import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {E,G,W,brief,panelDecisionBody,panelDecisionFixture,plan,sha256File} from './workflow-fixtures.mjs';

test('HTTP service serves built app and blocks foreign writes and unlisted files',async()=>{
  const httpProject=E.createProject({...brief,idea:'HTTP helper project'});E.saveProject(httpProject);
  const port=44918;const child=spawn(process.execPath,[path.join(W.APP,'server/server.mjs')],{env:{...process.env,PORT:String(port),WENDI_TEST_RESTART_NOOP:'1'},stdio:['ignore','pipe','pipe']});let output='';child.stderr.on('data',c=>output+=c);
  try{
    let ready=false;for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/health`);if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,50));}
    assert(ready,output);const base=`http://127.0.0.1:${port}`;
    const health=await (await fetch(base+'/api/health')).json();assert.equal(typeof health.instanceId,'string');assert(health.instanceId.length>3);
    const boot=await (await fetch(base+'/api/bootstrap')).json();assert(boot.connection.ready);assert(boot.references.length>=20);
    assert.equal(boot.connection.imageWorker.transport,'direct-chrome');assert.equal(boot.connection.imageWorker.browser,'chrome');assert.equal(boot.connection.imageWorker.state,'available');assert.equal(boot.connection.imageWorker.focusRestoration,'unsupported');assert.equal(boot.connection.imageWorker.focusSafe,false);assert.match(boot.connection.imageWorker.message,/站点访问权限将在任务中验证/);
    const refreshed=await (await fetch(base+'/api/connection',{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:'{}'})).json();assert.equal(refreshed.imageWorker.state,'available');assert.equal(refreshed.imageWorker.transport,'direct-chrome');assert.equal(refreshed.imageWorker.browser,'chrome');
    const terminalProject=E.createProject({...brief,idea:'HTTP 迟到接单终态一致性测试'});terminalProject.plan=structuredClone(plan);terminalProject.version=2;terminalProject.approved={version:2,hash:W.digest(terminalProject.plan)};terminalProject.samplesApproved=true;terminalProject.status='attention';
    const terminalDir=path.join(E.projectDir(terminalProject.id),'.制作记录','迟到终态'),terminalFile=path.join(E.projectDir(terminalProject.id),'v2','素材','终态占位.png'),terminalTaskId='http-late-terminal-task',terminalRequestId=crypto.randomUUID(),terminalAcceptedAt='2026-09-11T09:36:41+08:00';fs.mkdirSync(terminalDir,{recursive:true});fs.mkdirSync(path.dirname(terminalFile),{recursive:true});fs.writeFileSync(terminalFile,'fixture placeholder');
    fs.writeFileSync(path.join(terminalDir,'request.json'),JSON.stringify({schemaVersion:2,provider:G.WEB_IMAGE_PROVIDER,taskId:terminalTaskId,projectId:terminalProject.id,projectVersion:2,target:'第1页-第1格'}));fs.writeFileSync(path.join(terminalDir,'worker-request.json'),JSON.stringify({schemaVersion:2,provider:G.WEB_IMAGE_PROVIDER,requestId:terminalRequestId,projectId:terminalProject.id,projectVersion:2}));fs.writeFileSync(path.join(terminalDir,'web-generation.json'),JSON.stringify({provider:G.WEB_IMAGE_PROVIDER,state:'failed',accepted:true,requestId:terminalRequestId,acceptedAt:terminalAcceptedAt,submitted:false,errorCode:'IAB_UNAVAILABLE',error:'Codex IAB unavailable'}));
    terminalProject.pending={key:'第1页-第1格',file:terminalFile,dir:terminalDir,prompt:'终态一致性',refs:[],inputFiles:[],provider:G.WEB_IMAGE_PROVIDER,taskId:terminalTaskId,projectId:terminalProject.id,projectVersion:2,at:new Date().toISOString()};terminalProject.currentTask={id:terminalTaskId,kind:'image',target:'第1页-第1格',status:'not_accepted',errorCode:'WEB_WORKER_NOT_ACCEPTED',webState:'queued',providerInvocations:0};E.saveProject(terminalProject);
    const terminalBody=await (await fetch(base+`/api/projects/${terminalProject.id}`)).json();assert.equal(terminalBody.pending.requestId,terminalRequestId);assert.equal(terminalBody.pending.accepted,true);assert.equal(terminalBody.pending.webState,'failed');assert.equal(terminalBody.pending.errorCode,'IAB_UNAVAILABLE');assert.equal(terminalBody.currentTask.status,'failed');assert.equal(terminalBody.currentTask.webState,'failed');assert.equal(terminalBody.currentTask.errorCode,'IAB_UNAVAILABLE');
    fs.writeFileSync(path.join(terminalDir,'worker-request.json'),JSON.stringify({schemaVersion:2,provider:G.WEB_IMAGE_PROVIDER,requestId:crypto.randomUUID(),projectId:terminalProject.id,projectVersion:2}));const mismatchedBody=await (await fetch(base+`/api/projects/${terminalProject.id}`)).json();assert.equal(mismatchedBody.pending.webState,null);assert.equal(mismatchedBody.currentTask.status,'not_accepted');assert.equal(mismatchedBody.currentTask.webState,'queued');
    const qaSaved=E.createProject({...brief,idea:'HTTP QA 已保存终态文案测试'});qaSaved.status='attention';qaSaved.message='原图已保存，自动校对未完成，请人工查看；不会自动重生';qaSaved.error=qaSaved.message;qaSaved.currentTask={id:'qa-saved-task',kind:'image',target:'样张-1',status:'artifact_saved_unchecked',errorCode:'QA_UNAVAILABLE',providerInvocations:1,webState:'downloaded'};E.saveProject(qaSaved);
    const qaSavedBody=await (await fetch(base+`/api/projects/${qaSaved.id}`)).json();assert.equal(qaSavedBody.pending,null);assert.equal(qaSavedBody.status,'attention');assert.equal(qaSavedBody.message,qaSaved.message);assert.equal(qaSavedBody.error,qaSaved.message);assert.equal(qaSavedBody.currentTask.status,'artifact_saved_unchecked');assert.equal(qaSavedBody.currentTask.errorCode,'QA_UNAVAILABLE');
    assert.equal((await fetch(base+'/')).status,200);
    const switched=await (await fetch(base+`/api/projects/${httpProject.id}/settings`,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({model:'fixture-model',reasoningEffort:'low'})})).json();assert.equal(switched.brief.model,'fixture-model');assert.equal(switched.modelHistory.at(-1).to.model,'fixture-model');
    const renamed=await (await fetch(base+`/api/projects/${httpProject.id}/title`,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({title:'已改名的流程测试'})})).json();assert.equal(renamed.title,'已改名的流程测试');
    const panelAPI=E.createProject({...brief,idea:'正式分镜决定 API 幂等测试'});panelAPI.plan=structuredClone(plan);panelAPI.version=1;panelAPI.approved={version:1,hash:W.digest(panelAPI.plan)};panelAPI.samplesApproved=true;panelAPI.status='attention';const panelFile=path.join(E.projectDir(panelAPI.id),'v1','素材','api-panel.png'),panelRel=path.relative(E.projectDir(panelAPI.id),panelFile),panelAt=new Date().toISOString();fs.mkdirSync(path.dirname(panelFile),{recursive:true});fs.copyFileSync(W.inside(W.REFS,W.FACE[0]),panelFile);const panelIntegrity={sha256:sha256File(panelFile),sizeBytes:fs.statSync(panelFile).size};panelAPI.panels={'1-1':{key:'1-1',file:panelRel,prompt:'看书，手脚完整',refs:[],integrity:panelIntegrity,qa:{pass:false,status:'needs_review',summary:'API 测试失败质检',issues:['手部需要调整'],issueDetails:[{id:'formal-hand',category:'anatomy',severity:'review',description:'手部需要调整',repairAction:'review'}],repairPrompt:'人工确认'},at:panelAt}};panelAPI.artifacts=[{id:'image:第1页-第1格',kind:'image',file:panelRel,dependsOn:[],valid:true,at:panelAt,integrity:panelIntegrity}];panelAPI.panelDecision={state:'required',panelKey:'1-1',artifactId:'image:第1页-第1格',projectVersion:1,at:panelAt};E.saveProject(panelAPI);const panelBody={panelKey:'1-1',expectedRevision:panelAPI.revision,planHash:panelAPI.approved.hash,artifactId:'image:第1页-第1格',contentHash:W.digest({artifactId:'image:第1页-第1格',file:panelRel,at:panelAt}),decision:'accept_current',acknowledgedIssueIds:['formal-hand'],continueProduction:true,idempotencyKey:`panel:${panelAPI.id}:accept`},panelURL=base+`/api/projects/${panelAPI.id}/panel-decision`,panelResponse=await fetch(panelURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(panelBody)}),panelResponseBody=await panelResponse.json();assert.equal(panelResponse.status,200,JSON.stringify(panelResponseBody));const adopted=panelResponseBody;assert.equal(adopted.panels['1-1'].decision.action,'accept_current');const panelReplay=await fetch(panelURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(panelBody)});assert.equal(panelReplay.status,200);assert.equal((await panelReplay.json()).idempotent,true);const stale=await fetch(panelURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({...panelBody,idempotencyKey:`panel:${panelAPI.id}:stale`})});assert.equal(stale.status,409);
    const manualAPI=panelDecisionFixture('人工打回 API 本地幂等测试');manualAPI.project.panels['1-1'].qa={pass:true,status:'deferred',summary:'仅文件检查',issues:[],repairPrompt:''};E.saveProject(manualAPI.project);const manualIssue='意式机萃取头、手柄与出液口/液流位置关系不正确',manualBody={panelKey:'1-1',expectedRevision:manualAPI.project.revision,artifactId:manualAPI.artifactId,contentHash:W.digest({artifactId:manualAPI.artifactId,file:manualAPI.relative,at:manualAPI.at}),issue:manualIssue,repairPrompt:'只修正萃取头、portafilter 手柄卡口、双出液嘴与液流起点的功能连接，其他内容保持不变。',idempotencyKey:`manual:${manualAPI.project.id}:reject`},manualURL=base+`/api/projects/${manualAPI.project.id}/panel-review`,manualResponse=await fetch(manualURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(manualBody)}),manualResponseBody=await manualResponse.json();assert.equal(manualResponse.status,200,JSON.stringify(manualResponseBody));assert.equal(manualResponseBody.panels['1-1'].review.pass,false);assert.equal(manualResponseBody.panels['1-1'].review.status,'needs_review');assert.equal(manualResponseBody.panelDecision.state,'required');const manualReplay=await fetch(manualURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(manualBody)});assert.equal(manualReplay.status,200);assert.equal((await manualReplay.json()).idempotent,true);
    const missingHTTP=panelDecisionFixture('HTTP 缺失文件拒绝采用');fs.unlinkSync(missingHTTP.file);const missingHTTPResponse=await fetch(base+`/api/projects/${missingHTTP.project.id}/panel-decision`,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({...panelDecisionBody(missingHTTP),idempotencyKey:`panel:${missingHTTP.project.id}:missing`})});assert.equal(missingHTTPResponse.status,400);assert.equal(E.readProject(missingHTTP.project.id).panelDecisionCommands?.length||0,0);assert.equal(E.readProject(missingHTTP.project.id).panels['1-1'].userDecision,undefined);
    const corruptHTTP=panelDecisionFixture('HTTP 损坏文件拒绝采用');fs.writeFileSync(corruptHTTP.file,'not an image');const corruptHTTPResponse=await fetch(base+`/api/projects/${corruptHTTP.project.id}/panel-decision`,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({...panelDecisionBody(corruptHTTP),idempotencyKey:`panel:${corruptHTTP.project.id}:corrupt`})});assert.equal(corruptHTTPResponse.status,400);assert.equal(E.readProject(corruptHTTP.project.id).panelDecisionCommands?.length||0,0);assert.equal(E.readProject(corruptHTTP.project.id).panels['1-1'].userDecision,undefined);
    const retryable=E.createProject(brief);retryable.plan=structuredClone(plan);retryable.version=1;retryable.approved={version:1,hash:W.digest(retryable.plan)};retryable.samplesApproved=true;retryable.status='attention';retryable.pending=null;retryable.lastFailure=null;retryable.currentTask={id:'legacy-failed-task',kind:'image',target:'第1页-第1格',status:'failed_no_output',errorCode:'no-output',providerInvocations:1,completedAt:new Date().toISOString()};E.saveProject(retryable);
    const retryBody={confirmNoImage:true,idempotencyKey:`retry:${retryable.id}:fixture`},retryURL=base+`/api/projects/${retryable.id}/retry-missing`;
    const retried=await fetch(retryURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(retryBody)});assert.equal(retried.status,200);const retriedProject=await retried.json();assert.notEqual(retriedProject.error,'请先确认没有生成图片。');
    const replay=await (await fetch(retryURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(retryBody)})).json();assert.equal(replay.idempotent,true);
    const unknown=E.createProject({...brief,idea:'HTTP 未知结果重试测试'});unknown.plan=structuredClone(plan);unknown.version=1;unknown.approved={version:1,hash:W.digest(unknown.plan)};unknown.samplesApproved=true;unknown.status='attention';unknown.currentTask={id:'legacy-network-task',kind:'image',target:'第1页-第1格',status:'unknown_result',errorCode:'network',providerInvocations:1,completedAt:new Date().toISOString()};E.saveProject(unknown);
    const unknownURL=base+`/api/projects/${unknown.id}/retry-missing`,wrong=await fetch(unknownURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify({confirmNoImage:true,idempotencyKey:`retry-unknown:${unknown.id}:wrong`})});assert.notEqual(wrong.status,200);assert.match((await wrong.json()).error,/明确确认/);
    const unknownBody={confirmUnknownResult:true,idempotencyKey:`retry-unknown:${unknown.id}:approved`},approved=await fetch(unknownURL,{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:JSON.stringify(unknownBody)});assert.equal(approved.status,200);const approvedProject=await approved.json();assert.equal(approvedProject.retryCommands.at(-1).decision,'retry_unknown_result');
    assert.equal((await fetch(base+'/api/projects',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://untrusted.example','X-Wendi-Request':'studio'},body:JSON.stringify(brief)})).status,403);
    assert.equal((await fetch(base+'/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(brief)})).status,403);
    assert.equal((await fetch(base+'/media/project/'+httpProject.id+'/project.json')).status,404);
    assert.equal((await fetch(base+'/media/reference/'+encodeURIComponent('02-小林人设/小林人设1.png'))).status,404);
    const hostStatus=await new Promise((resolve,reject)=>{const r=http.get(base+'/api/health',{headers:{Host:'untrusted.example'}},res=>{res.resume();resolve(res.statusCode);});r.on('error',reject);});assert.equal(hostStatus,403);
    const response=await fetch(base+'/media/reference/'+W.FACE[0].split('/').map(encodeURIComponent).join('/'));assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'image/png');
    const busyRestart=await fetch(base+'/api/restart',{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:'{}'});assert.equal(busyRestart.status,409);
    let idle=false;for(let i=0;i<100;i++){const snapshot=await (await fetch(base+'/api/bootstrap')).json();if(snapshot.projects.every(project=>!project.busy)){idle=true;break;}await new Promise(resolve=>setTimeout(resolve,50));}assert(idle,'restart fixture jobs did not become idle');
    const restart=await fetch(base+'/api/restart',{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:'{}'}),restartBody=await restart.json();assert.equal(restart.status,202);assert.equal(restartBody.previousInstanceId,health.instanceId);
    const duplicateRestart=await fetch(base+'/api/restart',{method:'POST',headers:{'Content-Type':'application/json','X-Wendi-Request':'studio'},body:'{}'});assert.equal(duplicateRestart.status,409);
  }finally{
    if(child.exitCode===null){child.kill('SIGTERM');await new Promise(r=>{const timer=setTimeout(r,3000);child.once('close',()=>{clearTimeout(timer);r();});});}
  }
});
